algoritmo "semnome"
// Função :
// Autor :
// Data : 21/07/2020
// Seção de Declarações 
var
   nome:caractere
   valor:numerico

inicio
      // = IGUAL
      // > MAIOR QUE
      // <MENOR QUE
      //<> DIFERENTE DE
      //>= MAIOR OU IGUAL A
      //<=MENOR OU IGUAL A
      //escreva(5 = 5)
      //escreva(5<>5)
      //escreva ("mauricio" = "mauricio")
      // escreva ((5 = 5) = (5  > 6))
fimalgoritmo
